spring:
  profiles:
    active:
    - test #当前使用的环境
---
content: dev content  刷新出来看看
spring:
  profiles: dev    #开发环境
  application:
    name: config-client-dev
---
content test content
spring:
  profiles: test   #测试环境
  application:
    name: config-client-test